apiVersion: v1
kind: Service
metadata:
  name: log-output-svc
  namespace: dwk-mooc
spec:
  type: ClusterIP
  selector:
    app: log-output
  ports:
    - port: 2000
      protocol: TCP
      targetPort: 8080
