apiVersion: apps/v1
kind: Deployment
metadata:
  name: project
  namespace: dwk-mooc
  labels:
    app: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
        - name: log-output
          image: ghcr.io/fazstrac/dwk-project:1.6
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault