apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: log_output-ingress
  namespace: dwk-mooc  
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: log_output-svc
            port:
              number: 2345