when:
  - event: push
    branch: main

steps:
  - name: test
    image: golang:1.24-alpine
    commands:
      - go test -v  # Run tests in verbose mode  
  - name: build
    image: woodpeckerci/plugin-kaniko
    settings:
      registry: ghcr.io
      repo: fazstrac/dwk-project
      dockerfile: project/Containerfile
      context: project
      tags: ${CI_COMMIT_SHA}
      cache: true
      dry-run: false
      build_args:
      - COMMIT_SHA=${CI_COMMIT_SHA}
      - COMMIT_AUTHOR_EMAIL=${CI_COMMIT_AUTHOR_EMAIL}
      username: fazstrac
      password:
        from_secret: fudwin_repo_token