when:
  - event: push
    path:
      include: ['project/**', '.woodpecker/test.yaml']

steps:
  test:
    name: Run project app tests
    image: golang:1.24-alpine
    commands:
      - cd project
      - go test -v